call plug#begin()
Plug 'vimwiki/vimwiki'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'luochen1990/rainbow'
Plug 'airblade/vim-rooter'
Plug 'tpope/vim-commentary'
Plug 'junegunn/seoul256.vim'
Plug 'itchyny/lightline.vim'
Plug 'kshenoy/vim-signature'
Plug 'junegunn/vim-easy-align'
Plug 'easymotion/vim-easymotion'
Plug 'junegunn/goyo.vim'
Plug 'reedes/vim-pencil'
Plug 'junegunn/limelight.vim'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
call plug#end()

" reference: https://learnvimscriptthehardway.stevelosh.com/chapters/42.html
