#!/bin/sh

cd ~/all_git
for d in $(ls -d */); do
  cd $d && ls -a | grep -q .git && pwd && git status -s &&
  ls -a | grep -q .gitmodules && git submodule foreach git status -s ; cd ..
done

cd ~ && pwd && dotbare status -s
