#!/bin/sh

userresources=$HOME/.config/x11/xresources

# merge in defaults and keymaps

[ -f "$userresources" ] && xrdb -merge "$userresources"

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xset s off -dpms

exec i3
